ALTER TABLE `goal`
  ADD COLUMN `completed` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `isImportant` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);

CREATE TABLE IF NOT EXISTS `goalstats` (
  `id` VARCHAR(191) NOT NULL,
  `lifetimeGoalsCompleted` INTEGER NOT NULL DEFAULT 0,
  `lifetimeGoalsMissed` INTEGER NOT NULL DEFAULT 0,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT INTO `goalstats` (`id`, `lifetimeGoalsCompleted`, `lifetimeGoalsMissed`)
SELECT 'global', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM `goalstats` WHERE `id` = 'global');
